### ISSUE TITLE
No data received for a while

### ISSUE THREAD

**Issue by LoveMyData** [planningalerts-scrapers/canterbury#1]
Link seems have changed, try this one.

http://datrack.canterbury.nsw.gov.au/cgi/datrack.pl?lodgefrom=dd/mm/yyyy&lodgeto=dd/mm/yyyy&search=search

for pagination, look for 'Next' button and follow the link if exist

**Comment by CloCkWeRX** [comment]
This should be fixed; but it seems to have scraped a few years worth of data. Have since adjusted it to deal with only the first 15 pages and sort by date

**Comment by CloCkWeRX** [comment]
Manually ran revision d8055c92 and completed successfully 25 minutes ago.
run time 9 minutes
160 records added, 160 records removed in the database

I'm confused as to what's removing records - it's not the scraper, and the scraperwiki gem doesn't look like it should delete at first glance.

**Comment by CloCkWeRX** [comment]
@henare - see above. I'm fairly sure its all good; but...

**Comment by henare** [comment]
That normally means the magic to not overwrite records every time is not working. Have you checked that?

**Comment by CloCkWeRX** [comment]
I did check that it's explicitly avoiding existing records: https://github.com/planningalerts-scrapers/canterbury/blob/master/scraper.rb#L10

I couldn't find any explicit DELETEs in either this or the scraperwiki gem source; and it appeared to be "well, you've hit 5000 records; morph's going to clean up for you" - so I've run out of comprehension for magic.

Prior to the limit of 15 pages; it was trawling through up to 11,000 records total.

**Comment by LoveMyData** [comment]
Consider this is fixed.

Canterbury and Bankstown council are now merge, a new system should be coming up soon.
