### ISSUE TITLE
Failing on Morph

### ISSUE THREAD

**Issue by JasonThomasData** [planningalerts-scrapers/canterbury#4]
I've run this locally and can't get an error, it runs to 15 pages and then saves the database as expected.
To scrape the 15 pages, it did take some time so perhaps Morph times out for some reason?

**Comment by JasonThomasData** [comment]
Now I'm perplexed, since I created the same scraper for myself on Morph, here -https://morph.io/JasonThomasData/canterbury
And it passes with no errors.

Maybe this is an environment thing, so creating a new scraper might help? I'll leave it with you.

**Comment by LoveMyData** [comment]
@JasonThomasData, we thought the council merged with Bankstown and 'canterbury' domain was erroring with DNS not able to resolved it. so we turned off the scraper. It is now turned back on. Thanks for checking.
